# Generated by Django 3.1.5 on 2021-02-04 11:55

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.ImageField(blank=True, upload_to='barcode_images/')),
                ('country_id', models.CharField(max_length=2)),
                ('manufacturer_id', models.CharField(max_length=6)),
                ('product_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.IntegerField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', primary_key=True, serialize=False)),
                ('genre', models.TextField(help_text='For example: science, History, Technical, Enclyclopedia, etc.', max_length=20, null=True)),
                ('language', models.TextField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='book_image')),
                ('published_year', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Book Entry',
            },
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('member_name', models.CharField(max_length=200)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('expirydate', models.DateField(default=backend.models.get_expiry)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookentry')),
            ],
            options={
                'verbose_name_plural': 'Book Issue',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='avatar/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.member')),
            ],
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('member_name', models.CharField(max_length=200)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookissue')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.member')),
            ],
        ),
        migrations.CreateModel(
            name='BookRenew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('member_name', models.CharField(max_length=200)),
                ('renew_date', models.DateTimeField(auto_now_add=True)),
                ('expirydate', models.DateField(default=backend.models.get_expiry)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookissue')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.member')),
            ],
        ),
        migrations.AddField(
            model_name='bookissue',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.issue'),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.member'),
        ),
    ]
