# Generated by Django 3.1.5 on 2021-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.ImageField(blank=True, upload_to='barcode_images/')),
                ('country_id', models.CharField(max_length=1)),
                ('manufacturer_id', models.CharField(max_length=6)),
                ('product_id', models.CharField(max_length=5)),
            ],
        ),
    ]
