# Generated by Django 3.1.5 on 2021-02-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='issue_book_name',
            new_name='title',
        ),
    ]
