# Generated by Django 3.1.5 on 2021-02-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='isbn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookentry'),
        ),
    ]
