# Generated by Django 3.1.5 on 2021-01-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='country_id',
            field=models.CharField(max_length=2),
        ),
    ]
