# Generated by Django 3.1.5 on 2021-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210204_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='avatar/'),
        ),
    ]
