# Generated by Django 3.1.5 on 2021-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210201_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrenew',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bookissue',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookrenew',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookentry',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
